

trigger:
- main

pool:
  name: GAURAVNEWAGENT

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'vimgausris'
    backendAzureRmStorageAccountName: 'gauravvimstor'
    backendAzureRmContainerName: 'gauvimcon'
    backendAzureRmKey: 'tfstate'
